const MAINNET_SYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'sUSD',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0xb49f677943BC038e9857d61E7d053CaA2C1734C1',
    asset: 'EUR',
    category: 'forex',
    sign: '€',
    description: 'Euros',
    name: 'sEUR',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0xBcE206caE7f0ec07b545EddE332A47C2F75bbeb3',
    asset: 'JPY',
    category: 'forex',
    sign: '¥',
    description: 'Japanese Yen',
    name: 'sJPY',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x77F9710E7d0A19669A13c055F62cd80d313dF022',
    asset: 'AUD',
    category: 'forex',
    sign: '$',
    description: 'Australian Dollars',
    name: 'sAUD',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x5c0Ab2d9b5a7ed9f470386e82BB36A3613cDd4b5',
    asset: 'GBP',
    category: 'forex',
    sign: '£',
    description: 'Pound Sterling',
    name: 'sGBP',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x449d117117838fFA61263B61dA6301AA2a88B13A',
    asset: 'CHF',
    category: 'forex',
    sign: 'Fr',
    description: 'Swiss Franc',
    name: 'sCHF',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x01435677FB11763550905594A16B645847C1d0F3',
    asset: 'KRW',
    category: 'forex',
    sign: '₩',
    description: 'South Korean Won',
    name: 'sKRW',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Bitcoin',
    name: 'sBTC',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Ether',
    name: 'sETH',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    description: 'Chainlink',
    name: 'sLINK',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0xAE48c91dF1fE419994FFDa27da09D5aC69c30f55',
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    description: 'Cardano',
    name: 'sADA',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x547a514d5e3769680Ce22B2361c10Ea13619e8a9',
    asset: 'AAVE',
    category: 'crypto',
    sign: '',
    description: 'Aave',
    name: 'sAAVE',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x1C07AFb8E2B827c5A4739C6d59Ae3A5035f28734',
    asset: 'DOT',
    category: 'crypto',
    sign: '',
    description: 'Polkadot',
    name: 'sDOT',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0xAc559F25B1619171CbC396a50854A3240b6A4e99',
    asset: 'ETHBTC',
    category: 'crypto',
    sign: '',
    description: 'ETH / BTC',
    name: 'sETHBTC',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0xa8E875F94138B0C5b51d1e1d5dE35bbDdd28EA87',
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'DeFi Index',
    name: 'sDEFI',
    index: [
      {
        asset: 'UNI',
        category: 'crypto',
        sign: '',
        description: 'Uniswap',
        units: 66.3052,
        weight: 15,
      },
      {
        asset: 'AAVE',
        category: 'crypto',
        sign: '',
        description: 'Aave',
        feed: '0x547a514d5e3769680Ce22B2361c10Ea13619e8a9',
        units: 4.1634,
        weight: 11,
      },
      {
        asset: 'LUNA',
        category: 'crypto',
        sign: '',
        description: 'Terra Luna',
        units: 143.0753,
        weight: 10,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.3116,
        weight: 9,
      },
      {
        asset: 'SNX',
        category: 'crypto',
        sign: '',
        description: 'Synthetix Network Token',
        feed: '0xDC3EA94CD0AC27d9A86C180091e7f78C683d3699',
        units: 92.2672,
        weight: 8,
      },
      {
        asset: 'RUNE',
        category: 'crypto',
        sign: '',
        description: 'THORChain',
        units: 105.8407,
        weight: 8,
      },
      {
        asset: 'SUSHI',
        category: 'crypto',
        sign: '',
        description: 'SushiSwap',
        units: 78.2258,
        weight: 7,
      },
      {
        asset: 'COMP',
        category: 'crypto',
        sign: '',
        description: 'Compound',
        units: 2.2499,
        weight: 7,
      },
      {
        asset: 'YFI',
        category: 'crypto',
        sign: '',
        description: 'yearn.finance',
        units: 0.01503,
        weight: 6,
      },
      {
        asset: 'BNT',
        category: 'crypto',
        sign: '',
        description: 'Bancor',
        units: 74.5498,
        weight: 3,
      },
      {
        asset: 'UMA',
        category: 'crypto',
        sign: '',
        description: 'UMA',
        units: 25.608,
        weight: 3,
      },
      {
        asset: 'ZRX',
        category: 'crypto',
        sign: '',
        description: '0x',
        units: 294.7857,
        weight: 2.5,
      },
      {
        asset: 'CRV',
        category: 'crypto',
        sign: '',
        description: 'Curve DAO Token',
        units: 124.2496,
        weight: 2.5,
      },
      {
        asset: '1INCH',
        category: 'crypto',
        sign: '',
        description: '1inch',
        units: 59.0185,
        weight: 2,
      },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 440.8356,
        weight: 2,
      },
      {
        asset: 'BAL',
        category: 'crypto',
        sign: '',
        description: 'Balancer',
        units: 4.4333,
        weight: 1,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 57.667,
        weight: 1,
      },
      {
        asset: 'BOND',
        category: 'crypto',
        sign: '',
        description: 'Barnbridge',
        units: 2.274,
        weight: 1,
      },
      {
        asset: 'CREAM',
        category: 'crypto',
        sign: '',
        description: 'Cream Finance',
        units: 0.2667,
        weight: 0.5,
      },
      {
        asset: 'ALPHA',
        category: 'crypto',
        sign: '',
        description: 'Alpha Finance',
        units: 102.3121,
        weight: 0.5,
      },
    ],
    subclass: 'MultiCollateralSynth',
  },
];

const GOERLI_SYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'sUSD',
  },
  {
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Ether',
    feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419',
    name: 'sETH',
    subclass: 'MultiCollateralSynth',
  },
];

const KOVAN_SYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'sUSD',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x0c15Ab9A0DB086e062194c273CC79f41597Bbf13',
    asset: 'EUR',
    category: 'forex',
    sign: '€',
    description: 'Euros',
    name: 'sEUR',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0xD627B1eF3AC23F1d3e576FA6206126F3c1Bd0942',
    asset: 'JPY',
    category: 'forex',
    sign: '¥',
    description: 'Japanese Yen',
    name: 'sJPY',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x5813A90f826e16dB392abd2aF7966313fc1fd5B8',
    asset: 'AUD',
    category: 'forex',
    sign: '$',
    description: 'Australian Dollars',
    name: 'sAUD',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x28b0061f44E6A9780224AA61BEc8C3Fcb0d37de9',
    asset: 'GBP',
    category: 'forex',
    sign: '£',
    description: 'Pound Sterling',
    name: 'sGBP',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x9e465c5499023675051517E9Ee5f4C334D91e369',
    asset: 'KRW',
    category: 'forex',
    sign: '₩',
    description: 'South Korean Won',
    name: 'sKRW',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0xed0616BeF04D374969f302a34AE4A63882490A8C',
    asset: 'CHF',
    category: 'forex',
    sign: 'Fr',
    description: 'Swiss Franc',
    name: 'sCHF',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x6135b13325bfC4B00278B4abC5e20bbce2D6580e',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Bitcoin',
    name: 'sBTC',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x9326BFA02ADD2366b30bacB125260Af641031331',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Ether',
    name: 'sETH',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x396c5E36DD0a0F5a5D33dae44368D4193f69a1F0',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    description: 'Chainlink',
    name: 'sLINK',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x70179FB2F3A0a5b7FfB36a235599De440B0922ea',
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'DeFi Index',
    name: 'sDEFI',
    index: [
      {
        asset: 'COMP',
        category: 'crypto',
        sign: '',
        description: 'Compound',
        units: 1.55,
        weight: 5,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.54,
        weight: 10,
      },
      {
        asset: 'AAVE',
        category: 'crypto',
        sign: '',
        description: 'Aave',
        feed: '0x547a514d5e3769680Ce22B2361c10Ea13619e8a9',
        units: 4.72,
        weight: 15,
      },
      {
        asset: 'UMA',
        category: 'crypto',
        sign: '',
        description: 'UMA',
        units: 26.06,
        weight: 5,
      },
      {
        asset: 'SNX',
        category: 'crypto',
        sign: '',
        description: 'Synthetix Network Token',
        feed: '0x31f93DA9823d737b7E44bdee0DF389Fe62Fd1AcD',
        units: 87.2,
        weight: 15,
      },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 680.59,
        weight: 5,
      },
      {
        asset: 'UNI',
        category: 'crypto',
        sign: '',
        description: 'Uniswap',
        units: 100.71,
        weight: 15,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 334.06,
        weight: 5,
      },
      {
        asset: 'CRV',
        category: 'crypto',
        sign: '',
        description: 'Curve DAO Token',
        units: 254.94,
        weight: 5,
      },
      {
        asset: 'SUSHI',
        category: 'crypto',
        sign: '',
        description: 'SushiSwap',
        units: 43.111,
        weight: 5,
      },
      {
        asset: 'YFI',
        category: 'crypto',
        sign: '',
        description: 'yearn.finance',
        units: 0.01604,
        weight: 5,
      },
      {
        asset: 'BAL',
        category: 'crypto',
        sign: '',
        description: 'Balancer',
        units: 14.84,
        weight: 5,
      },
      {
        asset: 'BNT',
        category: 'crypto',
        sign: '',
        description: 'Bancor',
        units: 90.661,
        weight: 2.5,
      },
      {
        asset: '1INCH',
        category: 'crypto',
        sign: '',
        description: '1inch',
        units: 71.837,
        weight: 2.5,
      },
    ],
    subclass: 'MultiCollateralSynth',
  },
];

export default {
  1: MAINNET_SYNTHS,
  5: GOERLI_SYNTHS,
  42: KOVAN_SYNTHS,
};
