const MAINNET_SYNTHS = [
  {
    name: 'sEUR',
    asset: 'EUR',
    category: 'forex',
    sign: '€',
    desc: 'Euros',
    aggregator: '0x25Fa978ea1a7dc9bDc33a2959B9053EaE57169B5',
  },
  {
    name: 'sJPY',
    asset: 'JPY',
    category: 'forex',
    sign: '¥',
    desc: 'Japanese Yen',
    aggregator: '0xe1407BfAa6B5965BAd1C9f38316A3b655A09d8A6',
  },
  {
    name: 'sUSD',
    asset: 'USD',
    category: 'forex',
    sign: '$',
    desc: 'US Dollars',
  },
  {
    name: 'sAUD',
    asset: 'AUD',
    category: 'forex',
    sign: '$',
    desc: 'Australian Dollars',
    aggregator: '0x05Cf62c4bA0ccEA3Da680f9A8744Ac51116D6231',
  },
  {
    name: 'sGBP',
    asset: 'GBP',
    category: 'forex',
    sign: '£',
    desc: 'Pound Sterling',
    aggregator: '0x151445852B0cfDf6A4CC81440F2AF99176e8AD08',
  },
  {
    name: 'sCHF',
    asset: 'CHF',
    category: 'forex',
    sign: 'Fr',
    desc: 'Swiss Franc',
    aggregator: '0x02D5c618DBC591544b19d0bf13543c0728A3c4Ec',
  },
  {
    name: 'sXAU',
    asset: 'XAU',
    category: 'commodity',
    sign: 'oz',
    desc: 'Gold Ounce',
    aggregator: '0xafcE0c7b7fE3425aDb3871eAe5c0EC6d93E01935',
  },
  {
    name: 'sXAG',
    asset: 'XAG',
    category: 'commodity',
    sign: 'oz',
    desc: 'Silver Ounce',
    aggregator: '0x8946A183BFaFA95BEcf57c5e08fE5B7654d2807B',
  },
  {
    name: 'sBTC',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    desc: 'Bitcoin',
  },
  {
    name: 'sETH',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    desc: 'Ether',
    subclass: 'MultiCollateralSynth',
  },
  {
    name: 'sBNB',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    desc: 'Binance Coin',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'sTRX',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    desc: 'TRON',
  },
  {
    name: 'sXTZ',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    desc: 'Tezos',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'sXRP',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    desc: 'Ripple',
  },
  {
    name: 'sLTC',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    desc: 'Litecoin',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'sLINK',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    desc: 'Chainlink',
  },
  {
    name: 'sEOS',
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    desc: 'EOS',
  },
  {
    name: 'sBCH',
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    desc: 'Bitcoin Cash',
  },
  {
    name: 'sETC',
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    desc: 'Ethereum Classic',
  },
  {
    name: 'sDASH',
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    desc: 'Dash',
  },
  {
    name: 'sXMR',
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    desc: 'Monero',
  },
  {
    name: 'sADA',
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    desc: 'Cardano',
  },
  {
    name: 'sFTSE',
    asset: 'FTSE100',
    category: 'equities',
    sign: '',
    exchange: 'LSE',
    desc: 'FTSE 100 Index',
    aggregator: '0x16924ae9C2ac6cdbC9D6bB16FAfCD38BeD560936',
  },
  {
    name: 'sNIKKEI',
    asset: 'NIKKEI225',
    category: 'equities',
    sign: '',
    exchange: 'TSE',
    desc: 'Nikkei 225 Index',
    aggregator: '0x3f6E09A4EC3811765F5b2ad15c0279910dbb2c04',
  },
  {
    name: 'sCEX',
    asset: 'CEX',
    category: 'index',
    index: [
      { symbol: 'BNB', name: 'Binance Coin', units: 17.88 },
      { symbol: 'LEO', name: 'UNUS SED LEO', units: 153.85 },
      { symbol: 'HT', name: 'Huobi Token', units: 20.51 },
      { symbol: 'OKB', name: 'OKB', units: 32.52 },
      { symbol: 'KCS', name: 'KuCoin Shares', units: 59.82 },
    ],
    sign: '',
    desc: 'Centralised Exchange Index',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'sDEFI',
    asset: 'DEFI',
    category: 'index',
    index: [
      { symbol: 'LINK', name: 'Chainlink', units: 92.583 },
      { symbol: 'MKR', name: 'Maker', units: 0.432 },
      { symbol: 'ZRX', name: '0x', units: 502.718 },
      { symbol: 'SNX', name: 'Synthetix', units: 107.686 },
      { symbol: 'REN', name: 'Ren Protocol', units: 1222.393 },
      { symbol: 'LRC', name: 'Loopring', units: 2164.709 },
      { symbol: 'KNC', name: 'Kyber Network', units: 357.085 },
      { symbol: 'BNT', name: 'Bancor', units: 119.197 },
      { symbol: 'MLN', name: 'Melon Protocol', units: 6.495 },
    ],
    sign: '',
    desc: 'DeFi Index',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'iBTC',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    desc: 'Inverse Bitcoin',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 5275, upperLimit: 7912.5, lowerLimit: 2637.5 },
  },
  {
    name: 'iETH',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    desc: 'Inverse Ether',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 180.16, upperLimit: 270.24, lowerLimit: 90.08 },
  },
  {
    name: 'iBNB',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Binance Coin',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 16.13, upperLimit: 24.195, lowerLimit: 8.065 },
  },
  {
    name: 'iTRX',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    desc: 'Inverse TRON',
    subclass: 'PurgeableSynth',
    inverted: {
      entryPoint: 0.0101651,
      upperLimit: 0.0152476,
      lowerLimit: 0.0050825,
    },
  },
  {
    name: 'iXTZ',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Tezos',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 2.27, upperLimit: 3.405, lowerLimit: 1.135 },
  },
  {
    name: 'iXRP',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Ripple',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 0.15, upperLimit: 0.225, lowerLimit: 0.075 },
  },
  {
    name: 'iLINK',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Chainlink',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 3.66, upperLimit: 5.49, lowerLimit: 1.83 },
  },
  {
    name: 'iLTC',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Litecoin',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 35.66, upperLimit: 53.49, lowerLimit: 17.83 },
  },
  {
    name: 'iEOS',
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    desc: 'Inverse EOS',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 2.22, upperLimit: 3.33, lowerLimit: 1.11 },
  },
  {
    name: 'iBCH',
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Bitcoin Cash',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 218.33, upperLimit: 327.495, lowerLimit: 109.165 },
  },
  {
    name: 'iETC',
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Ethereum Classic',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 4.88, upperLimit: 7.32, lowerLimit: 2.44 },
  },
  {
    name: 'iDASH',
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Dash',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 64.44, upperLimit: 96.66, lowerLimit: 32.22 },
  },
  {
    name: 'iXMR',
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Monero',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 47.24, upperLimit: 70.86, lowerLimit: 23.62 },
  },
  {
    name: 'iADA',
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Cardano',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 0.031, upperLimit: 0.046, lowerLimit: 0.015 },
  },
  {
    name: 'iCEX',
    asset: 'CEX',
    category: 'index',
    index: [
      { symbol: 'BNB', name: 'Binance Coin', units: 17.88 },
      { symbol: 'LEO', name: 'UNUS SED LEO', units: 153.85 },
      { symbol: 'HT', name: 'Huobi Token', units: 20.51 },
      { symbol: 'OKB', name: 'OKB', units: 32.52 },
      { symbol: 'KCS', name: 'KuCoin Shares', units: 59.82 },
    ],
    sign: '',
    desc: 'Inverse Centralised Exchange Index',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 563.2, upperLimit: 844.8, lowerLimit: 281.6 },
  },
  {
    name: 'iDEFI',
    asset: 'DEFI',
    category: 'index',
    index: [
      { symbol: 'LINK', name: 'Chainlink', units: 92.583 },
      { symbol: 'MKR', name: 'Maker', units: 0.432 },
      { symbol: 'ZRX', name: '0x', units: 502.718 },
      { symbol: 'SNX', name: 'Synthetix', units: 107.686 },
      { symbol: 'REN', name: 'Ren Protocol', units: 1222.393 },
      { symbol: 'LRC', name: 'Loopring', units: 2164.709 },
      { symbol: 'KNC', name: 'Kyber Network', units: 357.085 },
      { symbol: 'BNT', name: 'Bancor', units: 119.197 },
      { symbol: 'MLN', name: 'Melon Protocol', units: 6.495 },
    ],
    sign: '',
    desc: 'Inverse DeFi Index',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 1000, upperLimit: 1500, lowerLimit: 500 },
  },
];

const ROPSTEN_SYNTHS = [
  {
    name: 'sEUR',
    asset: 'EUR',
    category: 'forex',
    sign: '€',
    desc: 'Euros',
    aggregator: '0xe95feDE497d0c02a2DBc8e20C5E8bFFE9339F03a',
  },
  {
    name: 'sJPY',
    asset: 'JPY',
    category: 'forex',
    sign: '¥',
    desc: 'Japanese Yen',
    aggregator: '0x8eAeBAF0eA3BC2a160b461703AF409d074CDEC6e',
  },
  {
    name: 'sUSD',
    asset: 'USD',
    category: 'forex',
    sign: '$',
    desc: 'US Dollars',
  },
  {
    name: 'sAUD',
    asset: 'AUD',
    category: 'forex',
    sign: '$',
    desc: 'Australian Dollars',
    aggregator: '0x1c621Aab85F7879690B5407404A097068770b59a',
  },
  {
    name: 'sGBP',
    asset: 'GBP',
    category: 'forex',
    sign: '£',
    desc: 'Pound Sterling',
    aggregator: '0xa2Dbd50FD09B9572a8A37ED4C2aEE4093A4b3Ef7',
  },
  {
    name: 'sCHF',
    asset: 'CHF',
    category: 'forex',
    sign: 'Fr',
    desc: 'Swiss Franc',
    aggregator: '0xD49c81796BccAbb5cd804f9d186B5E00E9Ac21fF',
  },
  {
    name: 'sXAU',
    asset: 'XAU',
    category: 'commodity',
    sign: 'oz',
    desc: 'Gold Ounce',
    aggregator: '0x2419A5aA4A82a6A18cA9b20Ea2934d7467E6a2cf',
  },
  {
    name: 'sXAG',
    asset: 'XAG',
    category: 'commodity',
    sign: 'oz',
    desc: 'Silver Ounce',
    aggregator: '0x42dE9E69B3a5a45600a11D3f37768dffA2846A8A',
  },
  {
    name: 'sBTC',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    desc: 'Bitcoin',
  },
  {
    name: 'sETH',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    desc: 'Ether',
    subclass: 'MultiCollateralSynth',
  },
  {
    name: 'sBNB',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    desc: 'Binance Coin',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'sTRX',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    desc: 'TRON',
  },
  {
    name: 'sXTZ',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    desc: 'Tezos',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'sXRP',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    desc: 'Ripple',
  },
  {
    name: 'sLTC',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    desc: 'Litecoin',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'sLINK',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    desc: 'Chainlink',
  },
  {
    name: 'sEOS',
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    desc: 'EOS',
  },
  {
    name: 'sBCH',
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    desc: 'Bitcoin Cash',
  },
  {
    name: 'sETC',
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    desc: 'Ethereum Classic',
  },
  {
    name: 'sDASH',
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    desc: 'Dash',
  },
  {
    name: 'sXMR',
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    desc: 'Monero',
  },
  {
    name: 'sADA',
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    desc: 'Cardano',
  },
  {
    name: 'sCEX',
    asset: 'CEX',
    category: 'index',
    index: [
      { symbol: 'BNB', name: 'Binance Coin', units: 17.88 },
      { symbol: 'LEO', name: 'UNUS SED LEO', units: 153.85 },
      { symbol: 'HT', name: 'Huobi Token', units: 20.51 },
      { symbol: 'OKB', name: 'OKB', units: 32.52 },
      { symbol: 'KCS', name: 'KuCoin Shares', units: 59.82 },
    ],
    sign: '',
    desc: 'Centralised Exchange Index',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'sDEFI',
    asset: 'DEFI',
    category: 'index',
    index: [
      { symbol: 'LINK', name: 'Chainlink', units: 92.583 },
      { symbol: 'MKR', name: 'Maker', units: 0.432 },
      { symbol: 'ZRX', name: '0x', units: 502.718 },
      { symbol: 'SNX', name: 'Synthetix', units: 107.686 },
      { symbol: 'REN', name: 'Ren Protocol', units: 1222.393 },
      { symbol: 'LRC', name: 'Loopring', units: 2164.709 },
      { symbol: 'KNC', name: 'Kyber Network', units: 357.085 },
      { symbol: 'BNT', name: 'Bancor', units: 119.197 },
      { symbol: 'MLN', name: 'Melon Protocol', units: 6.495 },
    ],
    sign: '',
    desc: 'DeFi Index',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'sFTSE',
    asset: 'FTSE100',
    category: 'equities',
    sign: '',
    exchange: 'LSE',
    desc: 'FTSE 100 Index',
    aggregator: '0xcC3A7753ee8a5C5969b068ed35eb5110b0c611A7',
  },
  {
    name: 'sNIKKEI',
    asset: 'NIKKEI225',
    category: 'equities',
    sign: '',
    exchange: 'TSE',
    desc: 'Nikkei 225 Index',
    aggregator: '0x95579a8376FFd7d66acDC1EC9992B7feDcb65854',
  },
  {
    name: 'iBTC',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    desc: 'Inverse Bitcoin',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 10600, upperLimit: 15900, lowerLimit: 5300 },
  },
  {
    name: 'iETH',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    desc: 'Inverse Ether',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 220, upperLimit: 330, lowerLimit: 110 },
  },
  {
    name: 'iBNB',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Binance Coin',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 22.258, upperLimit: 33.387, lowerLimit: 11.129 },
  },
  {
    name: 'iTRX',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    desc: 'Inverse TRON',
    subclass: 'PurgeableSynth',
    inverted: {
      entryPoint: 0.0186888,
      upperLimit: 0.0280332,
      lowerLimit: 0.0093444,
    },
  },
  {
    name: 'iXTZ',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Tezos',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 3.651, upperLimit: 5.4765, lowerLimit: 1.8255 },
  },
  {
    name: 'iXRP',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Ripple',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 0.2605, upperLimit: 0.3908, lowerLimit: 0.1303 },
  },
  {
    name: 'iLINK',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Chainlink',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 4.27296, upperLimit: 6.40944, lowerLimit: 2.13648 },
  },
  {
    name: 'iLTC',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Litecoin',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 58.73, upperLimit: 88.095, lowerLimit: 29.365 },
  },
  {
    name: 'iEOS',
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    desc: 'Inverse EOS',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 2.22, upperLimit: 3.33, lowerLimit: 1.11 },
  },
  {
    name: 'iBCH',
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Bitcoin Cash',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 218.33, upperLimit: 327.495, lowerLimit: 109.165 },
  },
  {
    name: 'iETC',
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Ethereum Classic',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 4.88, upperLimit: 7.32, lowerLimit: 2.44 },
  },
  {
    name: 'iDASH',
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Dash',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 64.44, upperLimit: 96.66, lowerLimit: 32.22 },
  },
  {
    name: 'iXMR',
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Monero',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 47.24, upperLimit: 70.86, lowerLimit: 23.62 },
  },
  {
    name: 'iADA',
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Cardano',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 0.031, upperLimit: 0.046, lowerLimit: 0.015 },
  },
  {
    name: 'iCEX',
    asset: 'CEX',
    category: 'index',
    index: [
      { symbol: 'BNB', name: 'Binance Coin', units: 17.88 },
      { symbol: 'LEO', name: 'UNUS SED LEO', units: 153.85 },
      { symbol: 'HT', name: 'Huobi Token', units: 20.51 },
      { symbol: 'OKB', name: 'OKB', units: 32.52 },
      { symbol: 'KCS', name: 'KuCoin Shares', units: 59.82 },
    ],
    sign: '',
    desc: 'Inverse Centralised Exchange Index',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 935, upperLimit: 1402.5, lowerLimit: 467.5 },
  },
  {
    name: 'iDEFI',
    asset: 'DEFI',
    category: 'index',
    index: [
      { symbol: 'LINK', name: 'Chainlink', units: 92.583 },
      { symbol: 'MKR', name: 'Maker', units: 0.432 },
      { symbol: 'ZRX', name: '0x', units: 502.718 },
      { symbol: 'SNX', name: 'Synthetix', units: 107.686 },
      { symbol: 'REN', name: 'Ren Protocol', units: 1222.393 },
      { symbol: 'LRC', name: 'Loopring', units: 2164.709 },
      { symbol: 'KNC', name: 'Kyber Network', units: 357.085 },
      { symbol: 'BNT', name: 'Bancor', units: 119.197 },
      { symbol: 'MLN', name: 'Melon Protocol', units: 6.495 },
    ],
    sign: '',
    desc: 'Inverse DeFi Index',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 1000, upperLimit: 1500, lowerLimit: 500 },
  },
];

const RINKEBY_SYNTHS = [
  {
    name: 'sEUR',
    asset: 'EUR',
    category: 'forex',
    sign: '€',
    desc: 'Euros',
    aggregator: '0x476d86Dfad0AEa4e33Cc728cd5aF0093f059368C',
  },
  {
    name: 'sJPY',
    asset: 'JPY',
    category: 'forex',
    sign: '¥',
    desc: 'Japanese Yen',
    aggregator: '0x5a7a8F877114bc15C3905D33f3733efe11b8eCb5',
  },
  {
    name: 'sUSD',
    asset: 'USD',
    category: 'forex',
    sign: '$',
    desc: 'US Dollars',
  },
  {
    name: 'sAUD',
    asset: 'AUD',
    category: 'forex',
    sign: '$',
    desc: 'Australian Dollars',
    aggregator: '0xaB1311577E6B96943eA2eB20B7f6C43844436D81',
  },
  {
    name: 'sGBP',
    asset: 'GBP',
    category: 'forex',
    sign: '£',
    desc: 'Pound Sterling',
    aggregator: '0x8653242ADcBfD3A2580d81143F2a07c91525F96f',
  },
  {
    name: 'sCHF',
    asset: 'CHF',
    category: 'forex',
    sign: 'Fr',
    desc: 'Swiss Franc',
    aggregator: '0xfFa1969B84670051779aa3aCD2dc350b810D361e',
  },
  {
    name: 'sXAU',
    asset: 'XAU',
    category: 'commodity',
    sign: 'oz',
    desc: 'Gold Ounce',
    aggregator: '0xE16f5B1F03D1db374091ecB915Dfce0b5E1C432c',
  },
  {
    name: 'sXAG',
    asset: 'XAG',
    category: 'commodity',
    sign: 'oz',
    desc: 'Silver Ounce',
    aggregator: '0x43953507c1c393efCd9502AB275D6aEa6aE75aFd',
  },
  {
    name: 'sBTC',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    desc: 'Bitcoin',
  },
  {
    name: 'sETH',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    desc: 'Ether',
    subclass: 'MultiCollateralSynth',
  },
  {
    name: 'sBNB',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    desc: 'Binance Coin',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'sTRX',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    desc: 'TRON',
  },
  {
    name: 'sXTZ',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    desc: 'Tezos',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'sXRP',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    desc: 'Ripple',
  },
  {
    name: 'sLTC',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    desc: 'Litecoin',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'sLINK',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    desc: 'Chainlink',
  },
  {
    name: 'sEOS',
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    desc: 'EOS',
  },
  {
    name: 'sBCH',
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    desc: 'Bitcoin Cash',
  },
  {
    name: 'sETC',
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    desc: 'Ethereum Classic',
  },
  {
    name: 'sDASH',
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    desc: 'Dash',
  },
  {
    name: 'sXMR',
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    desc: 'Monero',
  },
  {
    name: 'sADA',
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    desc: 'Cardano',
  },
  {
    name: 'sCEX',
    asset: 'CEX',
    category: 'index',
    index: [
      { symbol: 'BNB', name: 'Binance Coin', units: 17.88 },
      { symbol: 'LEO', name: 'UNUS SED LEO', units: 153.85 },
      { symbol: 'HT', name: 'Huobi Token', units: 20.51 },
      { symbol: 'OKB', name: 'OKB', units: 32.52 },
      { symbol: 'KCS', name: 'KuCoin Shares', units: 59.82 },
    ],
    sign: '',
    desc: 'Centralised Exchange Index',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'sDEFI',
    asset: 'DEFI',
    category: 'index',
    index: [
      { symbol: 'LINK', name: 'Chainlink', units: 92.583 },
      { symbol: 'MKR', name: 'Maker', units: 0.432 },
      { symbol: 'ZRX', name: '0x', units: 502.718 },
      { symbol: 'SNX', name: 'Synthetix', units: 107.686 },
      { symbol: 'REN', name: 'Ren Protocol', units: 1222.393 },
      { symbol: 'LRC', name: 'Loopring', units: 2164.709 },
      { symbol: 'KNC', name: 'Kyber Network', units: 357.085 },
      { symbol: 'BNT', name: 'Bancor', units: 119.197 },
      { symbol: 'MLN', name: 'Melon Protocol', units: 6.495 },
    ],
    sign: '',
    desc: 'DeFi Index',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'iBTC',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    desc: 'Inverse Bitcoin',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 10600, upperLimit: 15900, lowerLimit: 5300 },
  },
  {
    name: 'iETH',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    desc: 'Inverse Ether',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 220, upperLimit: 330, lowerLimit: 110 },
  },
  {
    name: 'iBNB',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Binance Coin',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 22.258, upperLimit: 33.387, lowerLimit: 11.129 },
  },
  {
    name: 'iTRX',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    desc: 'Inverse TRON',
    subclass: 'PurgeableSynth',
    inverted: {
      entryPoint: 0.0186888,
      upperLimit: 0.0280332,
      lowerLimit: 0.0093444,
    },
  },
  {
    name: 'iXTZ',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Tezos',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 3.651, upperLimit: 5.4765, lowerLimit: 1.8255 },
  },
  {
    name: 'iXRP',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Ripple',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 0.2605, upperLimit: 0.3908, lowerLimit: 0.1303 },
  },
  {
    name: 'iLINK',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Chainlink',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 4.27296, upperLimit: 6.40944, lowerLimit: 2.13648 },
  },
  {
    name: 'iLTC',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Litecoin',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 58.73, upperLimit: 88.095, lowerLimit: 29.365 },
  },
  {
    name: 'iEOS',
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    desc: 'Inverse EOS',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 2.22, upperLimit: 3.33, lowerLimit: 1.11 },
  },
  {
    name: 'iBCH',
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Bitcoin Cash',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 218.33, upperLimit: 327.495, lowerLimit: 109.165 },
  },
  {
    name: 'iETC',
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Ethereum Classic',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 4.88, upperLimit: 7.32, lowerLimit: 2.44 },
  },
  {
    name: 'iDASH',
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Dash',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 64.44, upperLimit: 96.66, lowerLimit: 32.22 },
  },
  {
    name: 'iXMR',
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Monero',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 47.24, upperLimit: 70.86, lowerLimit: 23.62 },
  },
  {
    name: 'iADA',
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Cardano',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 0.031, upperLimit: 0.046, lowerLimit: 0.015 },
  },
  {
    name: 'iCEX',
    asset: 'CEX',
    category: 'index',
    index: [
      { symbol: 'BNB', name: 'Binance Coin', units: 17.88 },
      { symbol: 'LEO', name: 'UNUS SED LEO', units: 153.85 },
      { symbol: 'HT', name: 'Huobi Token', units: 20.51 },
      { symbol: 'OKB', name: 'OKB', units: 32.52 },
      { symbol: 'KCS', name: 'KuCoin Shares', units: 59.82 },
    ],
    sign: '',
    desc: 'Inverse Centralised Exchange Index',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 935, upperLimit: 1402.5, lowerLimit: 467.5 },
  },
  {
    name: 'iDEFI',
    asset: 'DEFI',
    category: 'index',
    index: [
      { symbol: 'LINK', name: 'Chainlink', units: 92.583 },
      { symbol: 'MKR', name: 'Maker', units: 0.432 },
      { symbol: 'ZRX', name: '0x', units: 502.718 },
      { symbol: 'SNX', name: 'Synthetix', units: 107.686 },
      { symbol: 'REN', name: 'Ren Protocol', units: 1222.393 },
      { symbol: 'LRC', name: 'Loopring', units: 2164.709 },
      { symbol: 'KNC', name: 'Kyber Network', units: 357.085 },
      { symbol: 'BNT', name: 'Bancor', units: 119.197 },
      { symbol: 'MLN', name: 'Melon Protocol', units: 6.495 },
    ],
    sign: '',
    desc: 'Inverse DeFi Index',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 1000, upperLimit: 1500, lowerLimit: 500 },
  },
];

const KOVAN_SYNTHS = [
  {
    name: 'sEUR',
    asset: 'EUR',
    category: 'forex',
    sign: '€',
    desc: 'Euros',
    aggregator: '0xf23CCdA8333f658c43E7fC19aa00f6F5722eB225',
  },
  {
    name: 'sJPY',
    asset: 'JPY',
    category: 'forex',
    sign: '¥',
    desc: 'Japanese Yen',
    aggregator: '0xcd93a652e731Bb38eA9Efc5fEbCf977EDa2a01f7',
  },
  {
    name: 'sUSD',
    asset: 'USD',
    category: 'forex',
    sign: '$',
    desc: 'US Dollars',
  },
  {
    name: 'sAUD',
    asset: 'AUD',
    category: 'forex',
    sign: '$',
    desc: 'Australian Dollars',
    aggregator: '0xFD4767F2136F277ddd36b563504797C46a2eFF3B',
  },
  {
    name: 'sGBP',
    asset: 'GBP',
    category: 'forex',
    sign: '£',
    desc: 'Pound Sterling',
    aggregator: '0xbcf04560239e5A0D8e497E8215288fF8D25C026e',
  },
  {
    name: 'sCHF',
    asset: 'CHF',
    category: 'forex',
    sign: 'Fr',
    desc: 'Swiss Franc',
    aggregator: '0x3a982Ed122bF8e2bee035fCc6CAec894823E0129',
  },
  {
    name: 'sXAU',
    asset: 'XAU',
    category: 'commodity',
    sign: 'oz',
    desc: 'Gold Ounce',
    aggregator: '0xF1302340da93EdEF6DA03C66bc52F75A956e482C',
  },
  {
    name: 'sXAG',
    asset: 'XAG',
    category: 'commodity',
    sign: 'oz',
    desc: 'Silver Ounce',
    aggregator: '0x2447890E8b99f180e7BfA3386342CeA8EeDC64A3',
  },
  {
    name: 'sBTC',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    desc: 'Bitcoin',
  },
  {
    name: 'sETH',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    desc: 'Ether',
    subclass: 'MultiCollateralSynth',
  },
  {
    name: 'sBNB',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    desc: 'Binance Coin',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'sTRX',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    desc: 'TRON',
  },
  {
    name: 'sXTZ',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    desc: 'Tezos',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'sXRP',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    desc: 'Ripple',
  },
  {
    name: 'sLTC',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    desc: 'Litecoin',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'sLINK',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    desc: 'Chainlink',
  },
  {
    name: 'sEOS',
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    desc: 'EOS',
  },
  {
    name: 'sBCH',
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    desc: 'Bitcoin Cash',
  },
  {
    name: 'sETC',
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    desc: 'Ethereum Classic',
  },
  {
    name: 'sDASH',
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    desc: 'Dash',
  },
  {
    name: 'sXMR',
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    desc: 'Monero',
  },
  {
    name: 'sADA',
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    desc: 'Cardano',
  },
  {
    name: 'sCEX',
    asset: 'CEX',
    category: 'index',
    index: [
      { symbol: 'BNB', name: 'Binance Coin', units: 17.88 },
      { symbol: 'LEO', name: 'UNUS SED LEO', units: 153.85 },
      { symbol: 'HT', name: 'Huobi Token', units: 20.51 },
      { symbol: 'OKB', name: 'OKB', units: 32.52 },
      { symbol: 'KCS', name: 'KuCoin Shares', units: 59.82 },
    ],
    sign: '',
    desc: 'Centralised Exchange Index',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'sDEFI',
    asset: 'DEFI',
    category: 'index',
    index: [
      { symbol: 'LINK', name: 'Chainlink', units: 92.583 },
      { symbol: 'MKR', name: 'Maker', units: 0.432 },
      { symbol: 'ZRX', name: '0x', units: 502.718 },
      { symbol: 'SNX', name: 'Synthetix', units: 107.686 },
      { symbol: 'REN', name: 'Ren Protocol', units: 1222.393 },
      { symbol: 'LRC', name: 'Loopring', units: 2164.709 },
      { symbol: 'KNC', name: 'Kyber Network', units: 357.085 },
      { symbol: 'BNT', name: 'Bancor', units: 119.197 },
      { symbol: 'MLN', name: 'Melon Protocol', units: 6.495 },
    ],
    sign: '',
    desc: 'DeFi Index',
    subclass: 'PurgeableSynth',
  },
  {
    name: 'iBTC',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    desc: 'Inverse Bitcoin',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 5275, upperLimit: 7912.5, lowerLimit: 2637.5 },
  },
  {
    name: 'iETH',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    desc: 'Inverse Ether',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 122.43, upperLimit: 183.645, lowerLimit: 61.215 },
  },
  {
    name: 'iBNB',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Binance Coin',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 10.19, upperLimit: 15.285, lowerLimit: 5.095 },
  },
  {
    name: 'iTRX',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    desc: 'Inverse TRON',
    subclass: 'PurgeableSynth',
    inverted: {
      entryPoint: 0.0101651,
      upperLimit: 0.0152476,
      lowerLimit: 0.0050825,
    },
  },
  {
    name: 'iXTZ',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Tezos',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 1.49, upperLimit: 2.235, lowerLimit: 0.745 },
  },
  {
    name: 'iXRP',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Ripple',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 0.15, upperLimit: 0.225, lowerLimit: 0.075 },
  },
  {
    name: 'iLINK',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Chainlink',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 2.02, upperLimit: 3.03, lowerLimit: 1.01 },
  },
  {
    name: 'iLTC',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Litecoin',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 35.66, upperLimit: 53.49, lowerLimit: 17.83 },
  },
  {
    name: 'iEOS',
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    desc: 'Inverse EOS',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 2.22, upperLimit: 3.33, lowerLimit: 1.11 },
  },
  {
    name: 'iBCH',
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Bitcoin Cash',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 218.33, upperLimit: 327.495, lowerLimit: 109.165 },
  },
  {
    name: 'iETC',
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Ethereum Classic',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 4.88, upperLimit: 7.32, lowerLimit: 2.44 },
  },
  {
    name: 'iDASH',
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Dash',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 64.44, upperLimit: 96.66, lowerLimit: 32.22 },
  },
  {
    name: 'iXMR',
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Monero',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 47.24, upperLimit: 70.86, lowerLimit: 23.62 },
  },
  {
    name: 'iADA',
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    desc: 'Inverse Cardano',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 0.031, upperLimit: 0.046, lowerLimit: 0.015 },
  },
  {
    name: 'iCEX',
    asset: 'CEX',
    category: 'index',
    index: [
      { symbol: 'BNB', name: 'Binance Coin', units: 17.88 },
      { symbol: 'LEO', name: 'UNUS SED LEO', units: 153.85 },
      { symbol: 'HT', name: 'Huobi Token', units: 20.51 },
      { symbol: 'OKB', name: 'OKB', units: 32.52 },
      { symbol: 'KCS', name: 'KuCoin Shares', units: 59.82 },
    ],
    sign: '',
    desc: 'Inverse Centralised Exchange Index',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 563.2, upperLimit: 844.8, lowerLimit: 281.6 },
  },
  {
    name: 'iDEFI',
    asset: 'DEFI',
    category: 'index',
    index: [
      { symbol: 'LINK', name: 'Chainlink', units: 92.583 },
      { symbol: 'MKR', name: 'Maker', units: 0.432 },
      { symbol: 'ZRX', name: '0x', units: 502.718 },
      { symbol: 'SNX', name: 'Synthetix', units: 107.686 },
      { symbol: 'REN', name: 'Ren Protocol', units: 1222.393 },
      { symbol: 'LRC', name: 'Loopring', units: 2164.709 },
      { symbol: 'KNC', name: 'Kyber Network', units: 357.085 },
      { symbol: 'BNT', name: 'Bancor', units: 119.197 },
      { symbol: 'MLN', name: 'Melon Protocol', units: 6.495 },
    ],
    sign: '',
    desc: 'Inverse DeFi Index',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 1000, upperLimit: 1500, lowerLimit: 500 },
  },
];

export default {
  1: MAINNET_SYNTHS,
  3: ROPSTEN_SYNTHS,
  4: RINKEBY_SYNTHS,
  42: KOVAN_SYNTHS,
};
