const MAINNET_SYNTHS = [
  {
    name: 'XDR',
    category: 'internal',
    sign: '',
    desc: 'Synthetix Drawing Rights',
  },
  { name: 'sEUR', category: 'forex', sign: '€', desc: 'Euros' },
  {
    name: 'sJPY',
    category: 'forex',
    sign: '¥',
    desc: 'Japanese Yen',
  },
  { name: 'sUSD', category: 'forex', sign: '$', desc: 'US Dollars' },
  {
    name: 'sAUD',
    category: 'forex',
    sign: '$',
    desc: 'Australian Dollars',
  },
  {
    name: 'sKRW',
    category: 'forex',
    sign: '₩',
    desc: 'South Korean Won',
  },
  {
    name: 'sGBP',
    category: 'forex',
    sign: '£',
    desc: 'Pound Sterling',
  },
  {
    name: 'sCHF',
    category: 'forex',
    sign: 'Fr',
    desc: 'Swiss Franc',
  },
  {
    name: 'sCNY',
    category: 'forex',
    sign: '¥',
    desc: 'Chinese Yuan',
  },
  {
    name: 'sSGD',
    category: 'forex',
    sign: '$',
    desc: 'Singapore Dollar',
  },
  {
    name: 'sCAD',
    category: 'forex',
    sign: '$',
    desc: 'Canadian Dollar',
  },
  {
    name: 'sRUB',
    category: 'forex',
    sign: '₽',
    desc: 'Russian Ruble',
  },
  {
    name: 'sINR',
    category: 'forex',
    sign: '₹',
    desc: 'Indian Rupee',
  },
  {
    name: 'sBRL',
    category: 'forex',
    sign: 'R$',
    desc: 'Brazilian Real',
  },
  {
    name: 'sNZD',
    category: 'forex',
    sign: '$',
    desc: 'New Zealand Dollar',
  },
  {
    name: 'sPLN',
    category: 'forex',
    sign: 'zł',
    desc: 'Poland Złoty',
  },
  {
    name: 'sXAU',
    category: 'commodity',
    sign: 'oz',
    desc: 'Gold Ounce',
  },
  {
    name: 'sXAG',
    category: 'commodity',
    sign: 'oz',
    desc: 'Silver Ounce',
  },
  { name: 'sBTC', category: 'crypto', sign: '₿', desc: 'Bitcoin' },
];

const ROPSTEN_SYNTHS = [
  {
    name: 'XDR',
    category: 'internal',
    sign: '',
    desc: 'Synthetix Drawing Rights',
  },
  { name: 'sEUR', category: 'forex', sign: '€', desc: 'Euros' },
  {
    name: 'sJPY',
    category: 'forex',
    sign: '¥',
    desc: 'Japanese Yen',
  },
  { name: 'sUSD', category: 'forex', sign: '$', desc: 'US Dollars' },
  {
    name: 'sAUD',
    category: 'forex',
    sign: '$',
    desc: 'Australian Dollars',
  },
  {
    name: 'sKRW',
    category: 'forex',
    sign: '₩',
    desc: 'South Korean Won',
  },
  {
    name: 'sGBP',
    category: 'forex',
    sign: '£',
    desc: 'Pound Sterling',
  },
  {
    name: 'sCHF',
    category: 'forex',
    sign: 'Fr',
    desc: 'Swiss Franc',
  },
  {
    name: 'sCNY',
    category: 'forex',
    sign: '¥',
    desc: 'Chinese Yuan',
  },
  {
    name: 'sSGD',
    category: 'forex',
    sign: '$',
    desc: 'Singapore Dollar',
  },
  {
    name: 'sCAD',
    category: 'forex',
    sign: '$',
    desc: 'Canadian Dollar',
  },
  {
    name: 'sRUB',
    category: 'forex',
    sign: '₽',
    desc: 'Russian Ruble',
  },
  {
    name: 'sINR',
    category: 'forex',
    sign: '₹',
    desc: 'Indian Rupee',
  },
  {
    name: 'sBRL',
    category: 'forex',
    sign: 'R$',
    desc: 'Brazilian Real',
  },
  {
    name: 'sNZD',
    category: 'forex',
    sign: '$',
    desc: 'New Zealand Dollar',
  },
  {
    name: 'sPLN',
    category: 'forex',
    sign: 'zł',
    desc: 'Poland Złoty',
  },
  {
    name: 'sXAU',
    category: 'commodity',
    sign: 'oz',
    desc: 'Gold Ounce',
  },
  {
    name: 'sXAG',
    category: 'commodity',
    sign: 'oz',
    desc: 'Silver Ounce',
  },
  { name: 'sBTC', category: 'crypto', sign: '₿', desc: 'Bitcoin' },
];

const RINKEBY_SYNTHS = [
  {
    name: 'XDR',
    category: 'internal',
    sign: '',
    desc: 'Synthetix Drawing Rights',
  },
  { name: 'sEUR', category: 'forex', sign: '€', desc: 'Euros' },
  {
    name: 'sJPY',
    category: 'forex',
    sign: '¥',
    desc: 'Japanese Yen',
  },
  { name: 'sUSD', category: 'forex', sign: '$', desc: 'US Dollars' },
  {
    name: 'sAUD',
    category: 'forex',
    sign: '$',
    desc: 'Australian Dollars',
  },
  {
    name: 'sKRW',
    category: 'forex',
    sign: '₩',
    desc: 'South Korean Won',
  },
  {
    name: 'sGBP',
    category: 'forex',
    sign: '£',
    desc: 'Pound Sterling',
  },
  {
    name: 'sCHF',
    category: 'forex',
    sign: 'Fr',
    desc: 'Swiss Franc',
  },
  {
    name: 'sCNY',
    category: 'forex',
    sign: '¥',
    desc: 'Chinese Yuan',
  },
  {
    name: 'sSGD',
    category: 'forex',
    sign: '$',
    desc: 'Singapore Dollar',
  },
  {
    name: 'sCAD',
    category: 'forex',
    sign: '$',
    desc: 'Canadian Dollar',
  },
  {
    name: 'sRUB',
    category: 'forex',
    sign: '₽',
    desc: 'Russian Ruble',
  },
  {
    name: 'sINR',
    category: 'forex',
    sign: '₹',
    desc: 'Indian Rupee',
  },
  {
    name: 'sBRL',
    category: 'forex',
    sign: 'R$',
    desc: 'Brazilian Real',
  },
  {
    name: 'sNZD',
    category: 'forex',
    sign: '$',
    desc: 'New Zealand Dollar',
  },
  {
    name: 'sPLN',
    category: 'forex',
    sign: 'zł',
    desc: 'Poland Złoty',
  },
  {
    name: 'sXAU',
    category: 'commodity',
    sign: 'oz',
    desc: 'Gold Ounce',
  },
  {
    name: 'sXAG',
    category: 'commodity',
    sign: 'oz',
    desc: 'Silver Ounce',
  },
  { name: 'sBTC', category: 'crypto', sign: '₿', desc: 'Bitcoin' },
];

const KOVAN_SYNTHS = [
  {
    name: 'XDR',
    category: 'internal',
    sign: '',
    desc: 'Synthetix Drawing Rights',
  },
  { name: 'sEUR', category: 'forex', sign: '€', desc: 'Euros' },
  {
    name: 'sJPY',
    category: 'forex',
    sign: '¥',
    desc: 'Japanese Yen',
  },
  { name: 'sUSD', category: 'forex', sign: '$', desc: 'US Dollars' },
  {
    name: 'sAUD',
    category: 'forex',
    sign: '$',
    desc: 'Australian Dollars',
  },
  {
    name: 'sKRW',
    category: 'forex',
    sign: '₩',
    desc: 'South Korean Won',
  },
  {
    name: 'sGBP',
    category: 'forex',
    sign: '£',
    desc: 'Pound Sterling',
  },
  {
    name: 'sCHF',
    category: 'forex',
    sign: 'Fr',
    desc: 'Swiss Franc',
  },
  {
    name: 'sCNY',
    category: 'forex',
    sign: '¥',
    desc: 'Chinese Yuan',
  },
  {
    name: 'sSGD',
    category: 'forex',
    sign: '$',
    desc: 'Singapore Dollar',
  },
  {
    name: 'sCAD',
    category: 'forex',
    sign: '$',
    desc: 'Canadian Dollar',
  },
  {
    name: 'sRUB',
    category: 'forex',
    sign: '₽',
    desc: 'Russian Ruble',
  },
  {
    name: 'sINR',
    category: 'forex',
    sign: '₹',
    desc: 'Indian Rupee',
  },
  {
    name: 'sBRL',
    category: 'forex',
    sign: 'R$',
    desc: 'Brazilian Real',
  },
  {
    name: 'sNZD',
    category: 'forex',
    sign: '$',
    desc: 'New Zealand Dollar',
  },
  {
    name: 'sPLN',
    category: 'forex',
    sign: 'zł',
    desc: 'Poland Złoty',
  },
  {
    name: 'sXAU',
    category: 'commodity',
    sign: 'oz',
    desc: 'Gold Ounce',
  },
  {
    name: 'sXAG',
    category: 'commodity',
    sign: 'oz',
    desc: 'Silver Ounce',
  },
  { name: 'sBTC', category: 'crypto', sign: '₿', desc: 'Bitcoin' },
];

export default {
  1: MAINNET_SYNTHS,
  3: ROPSTEN_SYNTHS,
  4: RINKEBY_SYNTHS,
  42: KOVAN_SYNTHS,
};
