export default [
  {
    constant: false,
    inputs: [{ name: '_feePeriodDuration', type: 'uint256' }],
    name: 'setFeePeriodDuration',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x04c49f2c',
  },
  {
    constant: false,
    inputs: [{ name: '_feePoolState', type: 'address' }],
    name: 'setFeePoolState',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x075d2c41',
  },
  {
    constant: true,
    inputs: [{ name: 'account', type: 'address' }, { name: 'period', type: 'uint256' }],
    name: 'effectiveDebtRatioForPeriod',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x0813071c',
  },
  {
    constant: true,
    inputs: [],
    name: 'exchangeFeeRate',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x0f9b4955',
  },
  {
    constant: true,
    inputs: [{ name: 'account', type: 'address' }, { name: 'currencyKey', type: 'bytes4' }],
    name: 'feesAvailable',
    outputs: [{ name: '', type: 'uint256' }, { name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x10adda0e',
  },
  {
    constant: false,
    inputs: [{ name: '_owner', type: 'address' }],
    name: 'nominateNewOwner',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x1627540c',
  },
  {
    constant: true,
    inputs: [],
    name: 'initiationTime',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x17c70de4',
  },
  {
    constant: false,
    inputs: [{ name: '_beneficiary', type: 'address' }],
    name: 'setSelfDestructBeneficiary',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x20714f88',
  },
  {
    constant: true,
    inputs: [],
    name: 'feePeriodDuration',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x22425fa4',
  },
  {
    constant: true,
    inputs: [],
    name: 'feeAuthority',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x31dbd8a5',
  },
  {
    constant: false,
    inputs: [],
    name: 'terminateSelfDestruct',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x3278c960',
  },
  {
    constant: true,
    inputs: [{ name: 'account', type: 'address' }],
    name: 'feesByPeriod',
    outputs: [{ name: 'results', type: 'uint256[2][6]' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x33140016',
  },
  {
    constant: true,
    inputs: [],
    name: 'transferFeeRate',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x351bf518',
  },
  {
    constant: false,
    inputs: [],
    name: 'closeCurrentFeePeriod',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x3ebc457a',
  },
  {
    constant: true,
    inputs: [{ name: '', type: 'uint256' }],
    name: 'recentFeePeriods',
    outputs: [
      { name: 'feePeriodId', type: 'uint256' },
      { name: 'startingDebtIndex', type: 'uint256' },
      { name: 'startTime', type: 'uint256' },
      { name: 'feesToDistribute', type: 'uint256' },
      { name: 'feesClaimed', type: 'uint256' },
      { name: 'rewardsToDistribute', type: 'uint256' },
      { name: 'rewardsClaimed', type: 'uint256' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x3fcd2240',
  },
  {
    constant: true,
    inputs: [],
    name: 'nominatedOwner',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x53a47bb7',
  },
  {
    constant: false,
    inputs: [{ name: '_exchangeFeeRate', type: 'uint256' }],
    name: 'setExchangeFeeRate',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x578a791d',
  },
  {
    constant: true,
    inputs: [{ name: 'currencyKey', type: 'bytes4' }],
    name: 'totalFeesAvailable',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x639cd59c',
  },
  {
    constant: true,
    inputs: [],
    name: 'nextFeePeriodId',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x67fbc450',
  },
  {
    constant: true,
    inputs: [],
    name: 'totalRewardsAvailable',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x6de813f1',
  },
  {
    constant: true,
    inputs: [],
    name: 'synthetix',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x759b5225',
  },
  {
    constant: true,
    inputs: [],
    name: 'MAX_TRANSFER_FEE_RATE',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x76d752a1',
  },
  {
    constant: false,
    inputs: [],
    name: 'acceptOwnership',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x79ba5097',
  },
  {
    constant: false,
    inputs: [
      { name: 'account', type: 'address' },
      { name: 'debtRatio', type: 'uint256' },
      { name: 'debtEntryIndex', type: 'uint256' },
    ],
    name: 'appendAccountIssuanceRecord',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x86645274',
  },
  {
    constant: false,
    inputs: [{ name: '_feeAuthority', type: 'address' }],
    name: 'setFeeAuthority',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x8a957929',
  },
  {
    constant: true,
    inputs: [{ name: '', type: 'address' }],
    name: 'lastFeeWithdrawal',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x8cf61204',
  },
  {
    constant: true,
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x8da5cb5b',
  },
  {
    constant: false,
    inputs: [{ name: '_proxy', type: 'address' }],
    name: 'setProxy',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x97107d6d',
  },
  {
    constant: false,
    inputs: [],
    name: 'selfDestruct',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x9cb8a26a',
  },
  {
    constant: false,
    inputs: [{ name: 'currencyKey', type: 'bytes4' }, { name: 'amount', type: 'uint256' }],
    name: 'feePaid',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xa3fd6d0e',
  },
  {
    constant: true,
    inputs: [],
    name: 'rewardEscrow',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xa430be6c',
  },
  {
    constant: true,
    inputs: [],
    name: 'SELFDESTRUCT_DELAY',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xa461fc82',
  },
  {
    constant: false,
    inputs: [
      { name: 'feePeriodIndex', type: 'uint256' },
      { name: 'feePeriodId', type: 'uint256' },
      { name: 'startingDebtIndex', type: 'uint256' },
      { name: 'startTime', type: 'uint256' },
      { name: 'feesToDistribute', type: 'uint256' },
      { name: 'feesClaimed', type: 'uint256' },
      { name: 'rewardsToDistribute', type: 'uint256' },
      { name: 'rewardsClaimed', type: 'uint256' },
    ],
    name: 'importFeePeriod',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xb10090b8',
  },
  {
    constant: true,
    inputs: [{ name: 'value', type: 'uint256' }],
    name: 'exchangedAmountToReceive',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xb6dc8e25',
  },
  {
    constant: true,
    inputs: [{ name: 'value', type: 'uint256' }],
    name: 'amountReceivedFromTransfer',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xb7fcfa69',
  },
  {
    constant: true,
    inputs: [],
    name: 'selfDestructInitiated',
    outputs: [{ name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xb8225dec',
  },
  {
    constant: false,
    inputs: [{ name: 'sender', type: 'address' }],
    name: 'setMessageSender',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xbc67f832',
  },
  {
    constant: false,
    inputs: [],
    name: 'initiateSelfDestruct',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xbd32aa44',
  },
  {
    constant: true,
    inputs: [],
    name: 'selfDestructBeneficiary',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xc58aaae6',
  },
  {
    constant: false,
    inputs: [{ name: '_transferFeeRate', type: 'uint256' }],
    name: 'setTransferFeeRate',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xc894e1e5',
  },
  {
    constant: true,
    inputs: [{ name: 'value', type: 'uint256' }],
    name: 'exchangeFeeIncurred',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xcc9b31c9',
  },
  {
    constant: false,
    inputs: [{ name: 'currencyKey', type: 'bytes4' }],
    name: 'claimFees',
    outputs: [{ name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xcd503c0b',
  },
  {
    constant: true,
    inputs: [{ name: 'account', type: 'address' }],
    name: 'currentPenalty',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xcf427d1b',
  },
  {
    constant: true,
    inputs: [],
    name: 'FEE_PERIOD_LENGTH',
    outputs: [{ name: '', type: 'uint8' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xcff2ddad',
  },
  {
    constant: true,
    inputs: [],
    name: 'MIN_FEE_PERIOD_DURATION',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xd62ae399',
  },
  {
    constant: true,
    inputs: [{ name: 'value', type: 'uint256' }],
    name: 'transferFeeIncurred',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xda46e6c4',
  },
  {
    constant: true,
    inputs: [],
    name: 'synthetixState',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xdbd4a422',
  },
  {
    constant: true,
    inputs: [{ name: 'value', type: 'uint256' }],
    name: 'amountReceivedFromExchange',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xe05bac82',
  },
  {
    constant: true,
    inputs: [],
    name: 'feePoolState',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xe3082f6a',
  },
  {
    constant: false,
    inputs: [{ name: 'amount', type: 'uint256' }],
    name: 'rewardsMinted',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xe3f060ae',
  },
  {
    constant: true,
    inputs: [{ name: 'value', type: 'uint256' }],
    name: 'transferredAmountToReceive',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xe9d36c56',
  },
  {
    constant: true,
    inputs: [],
    name: 'FEE_ADDRESS',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xeb1edd61',
  },
  {
    constant: true,
    inputs: [],
    name: 'proxy',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xec556889',
  },
  {
    constant: true,
    inputs: [],
    name: 'MAX_FEE_PERIOD_DURATION',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xf344da67',
  },
  {
    constant: true,
    inputs: [],
    name: 'MAX_EXCHANGE_FEE_RATE',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xfb1b4c7e',
  },
  {
    constant: false,
    inputs: [{ name: '_synthetix', type: 'address' }],
    name: 'setSynthetix',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xfec9f9da',
  },
  {
    inputs: [
      { name: '_proxy', type: 'address' },
      { name: '_owner', type: 'address' },
      { name: '_synthetix', type: 'address' },
      { name: '_feePoolState', type: 'address' },
      { name: '_synthetixState', type: 'address' },
      { name: '_rewardEscrow', type: 'address' },
      { name: '_feeAuthority', type: 'address' },
      { name: '_transferFeeRate', type: 'uint256' },
      { name: '_exchangeFeeRate', type: 'uint256' },
    ],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'account', type: 'address' },
      { indexed: false, name: 'debtRatio', type: 'uint256' },
      { indexed: false, name: 'debtEntryIndex', type: 'uint256' },
      {
        indexed: false,
        name: 'feePeriodStartingDebtIndex',
        type: 'uint256',
      },
    ],
    name: 'IssuanceDebtRatioEntry',
    type: 'event',
    signature: '0x28dcdf40e6b6196065d54760038ab1a8c0c1d9cfa58a99e6b0cb6022f7e24775',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'newFeeRate', type: 'uint256' }],
    name: 'TransferFeeUpdated',
    type: 'event',
    signature: '0xf9f635b7cf851af6071aaf78ef8a5f752dc52f19d556fea4512b0c2ad4baea72',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'newFeeRate', type: 'uint256' }],
    name: 'ExchangeFeeUpdated',
    type: 'event',
    signature: '0xca0fe312a812d26dafe5eeab8fb96d69fbf83e7e5c71b4bb1e6d3f12fa0864d5',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'newFeePeriodDuration', type: 'uint256' }],
    name: 'FeePeriodDurationUpdated',
    type: 'event',
    signature: '0x791bd58dd9719b5eb5ccdd6ec4d5c459b0ab8efcf59b723cf477693c0889eacd',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'newFeeAuthority', type: 'address' }],
    name: 'FeeAuthorityUpdated',
    type: 'event',
    signature: '0xeb54700789b1b422a4c425a3586e928427c0fa693cb1d37146c9b3153ca701dd',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'newFeePoolState', type: 'address' }],
    name: 'FeePoolStateUpdated',
    type: 'event',
    signature: '0x0cb9b499f18f0c7abda1bcb83291bf288ccb1be624fe6bd5edc9bf605aab8fa5',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'feePeriodId', type: 'uint256' }],
    name: 'FeePeriodClosed',
    type: 'event',
    signature: '0xe2ca356e01eb0a4bb7caaf07d472b7d687db156713ffc3111c758e9fe0a17ea7',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: 'account', type: 'address' },
      { indexed: false, name: 'xdrAmount', type: 'uint256' },
    ],
    name: 'FeesClaimed',
    type: 'event',
    signature: '0x9493e5bbe4e8e0ac67284469a2d677403d0378a85a59e341d3abc433d0d9a209',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: 'account', type: 'address' },
      { indexed: false, name: 'snxAmount', type: 'uint256' },
    ],
    name: 'RewardsClaimed',
    type: 'event',
    signature: '0xfc30cddea38e2bf4d6ea7d3f9ed3b6ad7f176419f4963bd81318067a4aee73fe',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'newSynthetix', type: 'address' }],
    name: 'SynthetixUpdated',
    type: 'event',
    signature: '0x46e9c68bd7831071bdd478f1ae4c4a52463961a9d620383a0a121dbfc0e0f06d',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'SelfDestructTerminated',
    type: 'event',
    signature: '0x6adcc7125002935e0aa31697538ebbd65cfddf20431eb6ecdcfc3e238bfd082c',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'beneficiary', type: 'address' }],
    name: 'SelfDestructed',
    type: 'event',
    signature: '0x8a09e1677ced846cb537dc2b172043bd05a1a81ad7e0033a7ef8ba762df990b7',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'selfDestructDelay', type: 'uint256' }],
    name: 'SelfDestructInitiated',
    type: 'event',
    signature: '0xcbd94ca75b8dc45c9d80c77e851670e78843c0d75180cb81db3e2158228fa9a6',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'newBeneficiary', type: 'address' }],
    name: 'SelfDestructBeneficiaryUpdated',
    type: 'event',
    signature: '0xd5da63a0b864b315bc04128dedbc93888c8529ee6cf47ce664dc204339228c53',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'proxyAddress', type: 'address' }],
    name: 'ProxyUpdated',
    type: 'event',
    signature: '0xfc80377ca9c49cc11ae6982f390a42db976d5530af7c43889264b13fbbd7c57e',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'newOwner', type: 'address' }],
    name: 'OwnerNominated',
    type: 'event',
    signature: '0x906a1c6bd7e3091ea86693dd029a831c19049ce77f1dce2ce0bab1cacbabce22',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: 'oldOwner', type: 'address' },
      { indexed: false, name: 'newOwner', type: 'address' },
    ],
    name: 'OwnerChanged',
    type: 'event',
    signature: '0xb532073b38c83145e3e5135377a08bf9aab55bc0fd7c1179cd4fb995d2a5159c',
  },
];
