export default [
  {
    constant: false,
    inputs: [{ name: 'from', type: 'address' }, { name: 'amount', type: 'uint256' }],
    name: 'issueSynths',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x042e0688',
  },
  {
    constant: true,
    inputs: [],
    name: 'resolver',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x04f3bcec',
  },
  {
    constant: true,
    inputs: [],
    name: 'LAST_ISSUE_EVENT',
    outputs: [{ name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x129e05e6',
  },
  {
    constant: false,
    inputs: [{ name: '_owner', type: 'address' }],
    name: 'nominateNewOwner',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x1627540c',
  },
  {
    constant: true,
    inputs: [],
    name: 'minimumStakeTime',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x242df9e1',
  },
  {
    constant: false,
    inputs: [{ name: 'burnForAddress', type: 'address' }, { name: 'from', type: 'address' }],
    name: 'burnSynthsToTargetOnBehalf',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x2b3f41aa',
  },
  {
    constant: false,
    inputs: [{ name: '_resolver', type: 'address' }],
    name: 'setResolverAndSyncCache',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x3be99e6f',
  },
  {
    constant: false,
    inputs: [
      { name: 'issueForAddress', type: 'address' },
      { name: 'from', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'issueSynthsOnBehalf',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x44ec6b62',
  },
  {
    constant: false,
    inputs: [{ name: 'from', type: 'address' }],
    name: 'burnSynthsToTarget',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x497d704a',
  },
  {
    constant: true,
    inputs: [],
    name: 'nominatedOwner',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x53a47bb7',
  },
  {
    constant: true,
    inputs: [{ name: '_resolver', type: 'address' }],
    name: 'isResolverCached',
    outputs: [{ name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x631e1444',
  },
  {
    constant: false,
    inputs: [],
    name: 'acceptOwnership',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x79ba5097',
  },
  {
    constant: true,
    inputs: [],
    name: 'MAX_MINIMUM_STAKING_TIME',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x8ce2f55b',
  },
  {
    constant: true,
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x8da5cb5b',
  },
  {
    constant: false,
    inputs: [
      { name: 'burnForAddress', type: 'address' },
      { name: 'from', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'burnSynthsOnBehalf',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x9a5154b4',
  },
  {
    constant: false,
    inputs: [{ name: 'from', type: 'address' }, { name: 'amount', type: 'uint256' }],
    name: 'burnSynths',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xb06e8c65',
  },
  {
    constant: true,
    inputs: [{ name: 'account', type: 'address' }],
    name: 'canBurnSynths',
    outputs: [{ name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xbff4fdfc',
  },
  {
    constant: true,
    inputs: [{ name: '', type: 'uint256' }],
    name: 'resolverAddressesRequired',
    outputs: [{ name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xc6c9d828',
  },
  {
    constant: false,
    inputs: [{ name: 'from', type: 'address' }],
    name: 'issueMaxSynths',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xc8977132',
  },
  {
    constant: true,
    inputs: [{ name: 'account', type: 'address' }],
    name: 'lastIssueEvent',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xdd3d2b2e',
  },
  {
    constant: true,
    inputs: [],
    name: 'MAX_ADDRESSES_FROM_RESOLVER',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xe3235c91',
  },
  {
    constant: false,
    inputs: [{ name: '_seconds', type: 'uint256' }],
    name: 'setMinimumStakeTime',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xe9422046',
  },
  {
    constant: true,
    inputs: [],
    name: 'getResolverAddresses',
    outputs: [{ name: 'addresses', type: 'bytes32[24]' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xfa0b5168',
  },
  {
    constant: false,
    inputs: [{ name: 'issueForAddress', type: 'address' }, { name: 'from', type: 'address' }],
    name: 'issueMaxSynthsOnBehalf',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xfd864ccf',
  },
  {
    inputs: [{ name: '_owner', type: 'address' }, { name: '_resolver', type: 'address' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'constructor',
    signature: 'constructor',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'minimumStakeTime', type: 'uint256' }],
    name: 'MinimumStakeTimeUpdated',
    type: 'event',
    signature: '0x2b0fa66d155c9598699cb6569577f27b95729bbf580268eed39db6bc4e814477',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'newOwner', type: 'address' }],
    name: 'OwnerNominated',
    type: 'event',
    signature: '0x906a1c6bd7e3091ea86693dd029a831c19049ce77f1dce2ce0bab1cacbabce22',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: 'oldOwner', type: 'address' },
      { indexed: false, name: 'newOwner', type: 'address' },
    ],
    name: 'OwnerChanged',
    type: 'event',
    signature: '0xb532073b38c83145e3e5135377a08bf9aab55bc0fd7c1179cd4fb995d2a5159c',
  },
];
