export default [
  {
    constant: false,
    inputs: [{ name: '_owner', type: 'address' }],
    name: 'nominateNewOwner',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x1627540c',
  },
  {
    constant: false,
    inputs: [{ name: '_associatedContract', type: 'address' }],
    name: 'setAssociatedContract',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x52f445ca',
  },
  {
    constant: true,
    inputs: [],
    name: 'nominatedOwner',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x53a47bb7',
  },
  {
    constant: false,
    inputs: [{ name: 'authoriser', type: 'address' }, { name: 'delegate', type: 'address' }],
    name: 'withdrawApproval',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x5f0736a1',
  },
  {
    constant: false,
    inputs: [],
    name: 'acceptOwnership',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x79ba5097',
  },
  {
    constant: true,
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x8da5cb5b',
  },
  {
    constant: true,
    inputs: [],
    name: 'associatedContract',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xaefc4ccb',
  },
  {
    constant: false,
    inputs: [{ name: 'authoriser', type: 'address' }, { name: 'delegate', type: 'address' }],
    name: 'setApproval',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xb3c12354',
  },
  {
    constant: true,
    inputs: [{ name: '', type: 'address' }, { name: '', type: 'address' }],
    name: 'approval',
    outputs: [{ name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xe1270b6e',
  },
  {
    inputs: [{ name: '_owner', type: 'address' }, { name: '_associatedContract', type: 'address' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'authoriser', type: 'address' },
      { indexed: false, name: 'delegate', type: 'address' },
    ],
    name: 'Approval',
    type: 'event',
    signature: '0xf37f546c25e850257cc0c94f92bec94a17e2f0e884ddda268a25d8144b70eb6a',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'authoriser', type: 'address' },
      { indexed: false, name: 'delegate', type: 'address' },
    ],
    name: 'WithdrawApproval',
    type: 'event',
    signature: '0x16097899efec09cc50ee9db7218e30a5d8d6d2b2549c23e79568bf4a1a8c6f74',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'associatedContract', type: 'address' }],
    name: 'AssociatedContractUpdated',
    type: 'event',
    signature: '0x73f20cff579e8a4086fa607db83867595f1b6a798e718c0bfa0b94a404128e03',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'newOwner', type: 'address' }],
    name: 'OwnerNominated',
    type: 'event',
    signature: '0x906a1c6bd7e3091ea86693dd029a831c19049ce77f1dce2ce0bab1cacbabce22',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: 'oldOwner', type: 'address' },
      { indexed: false, name: 'newOwner', type: 'address' },
    ],
    name: 'OwnerChanged',
    type: 'event',
    signature: '0xb532073b38c83145e3e5135377a08bf9aab55bc0fd7c1179cd4fb995d2a5159c',
  },
];
