export default [
  {
    inputs: [
      { internalType: 'address', name: '_owner', type: 'address' },
      { internalType: 'address', name: '_resolver', type: 'address' },
      { internalType: 'bytes32', name: '_baseAsset', type: 'bytes32' },
      {
        internalType: 'uint256',
        name: '_exchangeFee',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '_maxLeverage',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '_maxMarketDebt',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '_minInitialMargin',
        type: 'uint256',
      },
      {
        internalType: 'uint256[3]',
        name: '_fundingParameters',
        type: 'uint256[3]',
      },
    ],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'constructor',
    signature: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'fee',
        type: 'uint256',
      },
    ],
    name: 'ExchangeFeeUpdated',
    type: 'event',
    signature: '0xca0fe312a812d26dafe5eeab8fb96d69fbf83e7e5c71b4bb1e6d3f12fa0864d5',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'maxFundingRate',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'maxFundingRateSkew',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'maxFundingRateDelta',
        type: 'uint256',
      },
    ],
    name: 'FundingParametersUpdated',
    type: 'event',
    signature: '0xe57a525c7bde85f829580dcdeb6c9534bda4765ac5a6c2e4a54343cbcf8a3b74',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'leverage',
        type: 'uint256',
      },
    ],
    name: 'MaxLeverageUpdated',
    type: 'event',
    signature: '0xb0f01601e93ad2a8fc4106e97567bc037aa114741705be9d80570fd2afa7bf1b',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'cap',
        type: 'uint256',
      },
    ],
    name: 'MaxMarketDebtUpdated',
    type: 'event',
    signature: '0xd919bdc3e79deaa8a0737499fbce11cd4d7f210feeddef95115c888db23660e8',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'minMargin',
        type: 'uint256',
      },
    ],
    name: 'MinInitialMarginUpdated',
    type: 'event',
    signature: '0xf5958b2492f4eeb807d26adb1e05d927402a2b27ec6b67e98a76def8bf9fbb99',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'OrderCancelled',
    type: 'event',
    signature: '0x6b8212b205b721ddcff41db420898b1132d4f1400798c1770b4e3c52498c05ef',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'int256',
        name: 'margin',
        type: 'int256',
      },
      {
        indexed: false,
        internalType: 'int256',
        name: 'size',
        type: 'int256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'fee',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'entryPrice',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'entryIndex',
        type: 'uint256',
      },
    ],
    name: 'OrderConfirmed',
    type: 'event',
    signature: '0x60a8f5b575cea3f3176dbc7f270eb58bef926a5386f799e3415a274c538f0f54',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'int256',
        name: 'margin',
        type: 'int256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'leverage',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'fee',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'roundId',
        type: 'uint256',
      },
    ],
    name: 'OrderSubmitted',
    type: 'event',
    signature: '0xbc0f4a6c775328ead0a534bfa9109b877aa2f216e3d89a293b0899f110a535c6',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'oldOwner',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnerChanged',
    type: 'event',
    signature: '0xb532073b38c83145e3e5135377a08bf9aab55bc0fd7c1179cd4fb995d2a5159c',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnerNominated',
    type: 'event',
    signature: '0x906a1c6bd7e3091ea86693dd029a831c19049ce77f1dce2ce0bab1cacbabce22',
  },
  {
    constant: true,
    inputs: [],
    name: 'MAX_ADDRESSES_FROM_RESOLVER',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xe3235c91',
  },
  {
    constant: false,
    inputs: [],
    name: 'acceptOwnership',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x79ba5097',
  },
  {
    constant: true,
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'accruedFunding',
    outputs: [
      { internalType: 'int256', name: 'funding', type: 'int256' },
      { internalType: 'bool', name: 'isInvalid', type: 'bool' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x1bf556d0',
  },
  {
    constant: true,
    inputs: [],
    name: 'baseAsset',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xcdf456e1',
  },
  {
    constant: false,
    inputs: [],
    name: 'cancelOrder',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x6a816548',
  },
  {
    constant: false,
    inputs: [],
    name: 'closePosition',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xc393d0e3',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'confirmOrder',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x7ee9e2d8',
  },
  {
    constant: true,
    inputs: [],
    name: 'currentFundingRate',
    outputs: [{ internalType: 'int256', name: '', type: 'int256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x3aef4d0b',
  },
  {
    constant: true,
    inputs: [],
    name: 'currentRoundId',
    outputs: [{ internalType: 'uint256', name: 'roundId', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x9cbe5efd',
  },
  {
    constant: true,
    inputs: [],
    name: 'entryMarginSumMinusNotionalSkew',
    outputs: [{ internalType: 'int256', name: '', type: 'int256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xfd3a534b',
  },
  {
    constant: true,
    inputs: [],
    name: 'entryNotionalSkew',
    outputs: [{ internalType: 'int256', name: '', type: 'int256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xf542ec4c',
  },
  {
    constant: true,
    inputs: [],
    name: 'exchangeFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x2ecd3be4',
  },
  {
    constant: true,
    inputs: [],
    name: 'fundingLastRecomputed',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x27b9a236',
  },
  {
    constant: true,
    inputs: [],
    name: 'fundingParameters',
    outputs: [
      {
        internalType: 'uint256',
        name: 'maxFundingRate',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'maxFundingRateSkew',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'maxFundingRateDelta',
        type: 'uint256',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x84924bcd',
  },
  {
    constant: true,
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'fundingSequence',
    outputs: [{ internalType: 'int256', name: '', type: 'int256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x41108cf2',
  },
  {
    constant: true,
    inputs: [],
    name: 'getResolverAddressesRequired',
    outputs: [
      {
        internalType: 'bytes32[24]',
        name: 'addressesRequired',
        type: 'bytes32[24]',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xab49848c',
  },
  {
    constant: true,
    inputs: [
      {
        internalType: 'contract AddressResolver',
        name: '_resolver',
        type: 'address',
      },
    ],
    name: 'isResolverCached',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x631e1444',
  },
  {
    constant: true,
    inputs: [
      { internalType: 'address', name: 'account', type: 'address' },
      { internalType: 'bool', name: 'includeFunding', type: 'bool' },
    ],
    name: 'liquidationPrice',
    outputs: [{ internalType: 'uint256', name: 'price', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xbd2dcd38',
  },
  {
    constant: true,
    inputs: [],
    name: 'marketDebt',
    outputs: [
      { internalType: 'uint256', name: 'debt', type: 'uint256' },
      { internalType: 'bool', name: 'isInvalid', type: 'bool' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xe8c63470',
  },
  {
    constant: true,
    inputs: [],
    name: 'marketSize',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xeb56105d',
  },
  {
    constant: true,
    inputs: [],
    name: 'marketSizes',
    outputs: [
      { internalType: 'uint256', name: 'short', type: 'uint256' },
      { internalType: 'uint256', name: 'long', type: 'uint256' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x5fc890c2',
  },
  {
    constant: true,
    inputs: [],
    name: 'marketSkew',
    outputs: [{ internalType: 'int256', name: '', type: 'int256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x2b58ecef',
  },
  {
    constant: true,
    inputs: [],
    name: 'maxLeverage',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xae3302c2',
  },
  {
    constant: true,
    inputs: [],
    name: 'maxMarketDebt',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x5c57f6d8',
  },
  {
    constant: true,
    inputs: [],
    name: 'minInitialMargin',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x8f20f2ea',
  },
  {
    constant: true,
    inputs: [
      { internalType: 'uint256', name: 'startIndex', type: 'uint256' },
      { internalType: 'uint256', name: 'endIndex', type: 'uint256' },
    ],
    name: 'netFundingPerUnit',
    outputs: [
      { internalType: 'int256', name: 'funding', type: 'int256' },
      { internalType: 'bool', name: 'isInvalid', type: 'bool' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xbb5b2645',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: '_owner', type: 'address' }],
    name: 'nominateNewOwner',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x1627540c',
  },
  {
    constant: true,
    inputs: [],
    name: 'nominatedOwner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x53a47bb7',
  },
  {
    constant: true,
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'notionalValue',
    outputs: [
      { internalType: 'int256', name: 'value', type: 'int256' },
      { internalType: 'bool', name: 'isInvalid', type: 'bool' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xb895daab',
  },
  {
    constant: true,
    inputs: [
      { internalType: 'address', name: 'account', type: 'address' },
      { internalType: 'int256', name: 'margin', type: 'int256' },
      { internalType: 'uint256', name: 'leverage', type: 'uint256' },
    ],
    name: 'orderFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x6201a40a',
  },
  {
    constant: true,
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'orders',
    outputs: [
      { internalType: 'bool', name: 'pending', type: 'bool' },
      { internalType: 'int256', name: 'margin', type: 'int256' },
      { internalType: 'uint256', name: 'leverage', type: 'uint256' },
      { internalType: 'uint256', name: 'fee', type: 'uint256' },
      { internalType: 'uint256', name: 'roundId', type: 'uint256' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xf40e8471',
  },
  {
    constant: true,
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x8da5cb5b',
  },
  {
    constant: true,
    inputs: [],
    name: 'pendingOrderValue',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x0676ad63',
  },
  {
    constant: true,
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'positions',
    outputs: [
      { internalType: 'int256', name: 'margin', type: 'int256' },
      { internalType: 'int256', name: 'size', type: 'int256' },
      { internalType: 'uint256', name: 'entryPrice', type: 'uint256' },
      { internalType: 'uint256', name: 'entryIndex', type: 'uint256' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x55f57510',
  },
  {
    constant: true,
    inputs: [],
    name: 'priceAndInvalid',
    outputs: [
      { internalType: 'uint256', name: 'assetPrice', type: 'uint256' },
      { internalType: 'bool', name: 'isInvalid', type: 'bool' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x406bcd7b',
  },
  {
    constant: true,
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'profitLoss',
    outputs: [
      { internalType: 'int256', name: 'pnl', type: 'int256' },
      { internalType: 'bool', name: 'isInvalid', type: 'bool' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xb111dfac',
  },
  {
    constant: true,
    inputs: [],
    name: 'proportionalSkew',
    outputs: [{ internalType: 'int256', name: '', type: 'int256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xc115e443',
  },
  {
    constant: true,
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'remainingMargin',
    outputs: [
      {
        internalType: 'int256',
        name: 'marginRemaining',
        type: 'int256',
      },
      { internalType: 'bool', name: 'isInvalid', type: 'bool' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x9cfbf4e4',
  },
  {
    constant: true,
    inputs: [],
    name: 'resolver',
    outputs: [
      {
        internalType: 'contract AddressResolver',
        name: '',
        type: 'address',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x04f3bcec',
  },
  {
    constant: true,
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'resolverAddressesRequired',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xc6c9d828',
  },
  {
    constant: false,
    inputs: [{ internalType: 'uint256', name: 'fee', type: 'uint256' }],
    name: 'setExchangeFee',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x9df8cc7b',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'uint256',
        name: 'maxFundingRate',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'maxFundingRateSkew',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'maxFundingRateDelta',
        type: 'uint256',
      },
    ],
    name: 'setFundingParameters',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x09bf55cb',
  },
  {
    constant: false,
    inputs: [{ internalType: 'uint256', name: 'leverage', type: 'uint256' }],
    name: 'setMaxLeverage',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xd3127e63',
  },
  {
    constant: false,
    inputs: [{ internalType: 'uint256', name: 'cap', type: 'uint256' }],
    name: 'setMaxMarketDebt',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x062d8bc7',
  },
  {
    constant: false,
    inputs: [{ internalType: 'uint256', name: 'minMargin', type: 'uint256' }],
    name: 'setMinInitialMargin',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x20edcdb8',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'contract AddressResolver',
        name: '_resolver',
        type: 'address',
      },
    ],
    name: 'setResolverAndSyncCache',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x3be99e6f',
  },
  {
    constant: false,
    inputs: [
      { internalType: 'int256', name: 'margin', type: 'int256' },
      { internalType: 'uint256', name: 'leverage', type: 'uint256' },
    ],
    name: 'submitOrder',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xf99b0820',
  },
  {
    constant: true,
    inputs: [],
    name: 'unrecordedFunding',
    outputs: [
      { internalType: 'int256', name: 'funding', type: 'int256' },
      { internalType: 'bool', name: 'isInvalid', type: 'bool' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x917e77f5',
  },
];
