export default [
  {
    inputs: [
      { internalType: 'address', name: '_owner', type: 'address' },
      {
        internalType: 'contract EternalStorage',
        name: '_eternalStorage',
        type: 'address',
      },
    ],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'constructor',
    signature: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'authoriser',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'delegate',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'action',
        type: 'bytes32',
      },
    ],
    name: 'Approval',
    type: 'event',
    signature: '0x36a9e0c1da9cdc6d8f4bd4cb261f9ad6a45eb1641a557ead7530fbeff9a26336',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'newEternalStorage',
        type: 'address',
      },
    ],
    name: 'EternalStorageUpdated',
    type: 'event',
    signature: '0xe3ebe3d58e84fbd094152babb730cf99a14b47f65ed04f35a3bd6356f8161a17',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'oldOwner',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnerChanged',
    type: 'event',
    signature: '0xb532073b38c83145e3e5135377a08bf9aab55bc0fd7c1179cd4fb995d2a5159c',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnerNominated',
    type: 'event',
    signature: '0x906a1c6bd7e3091ea86693dd029a831c19049ce77f1dce2ce0bab1cacbabce22',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'authoriser',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'delegate',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'action',
        type: 'bytes32',
      },
    ],
    name: 'WithdrawApproval',
    type: 'event',
    signature: '0x7e8dc09322ac82342d9dbfd49eb6497fa7ab69ac444f3763a9b8e16530342f41',
  },
  {
    constant: true,
    inputs: [],
    name: 'APPROVE_ALL',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x9cbc2ebe',
  },
  {
    constant: true,
    inputs: [],
    name: 'BURN_FOR_ADDRESS',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xe32b3f52',
  },
  {
    constant: true,
    inputs: [],
    name: 'CLAIM_FOR_ADDRESS',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xc5e17ab0',
  },
  {
    constant: true,
    inputs: [],
    name: 'EXCHANGE_FOR_ADDRESS',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xd8eeb7c1',
  },
  {
    constant: true,
    inputs: [],
    name: 'ISSUE_FOR_ADDRESS',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x2c70aecf',
  },
  {
    constant: false,
    inputs: [],
    name: 'acceptOwnership',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x79ba5097',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: 'delegate', type: 'address' }],
    name: 'approveAllDelegatePowers',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xbc87acbf',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: 'delegate', type: 'address' }],
    name: 'approveBurnOnBehalf',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x9c79ce35',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: 'delegate', type: 'address' }],
    name: 'approveClaimOnBehalf',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x4180e5b5',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: 'delegate', type: 'address' }],
    name: 'approveExchangeOnBehalf',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x447fbc63',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: 'delegate', type: 'address' }],
    name: 'approveIssueOnBehalf',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x9f61d336',
  },
  {
    constant: true,
    inputs: [
      { internalType: 'address', name: 'authoriser', type: 'address' },
      { internalType: 'address', name: 'delegate', type: 'address' },
    ],
    name: 'approvedAll',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xb42e0f15',
  },
  {
    constant: true,
    inputs: [
      { internalType: 'address', name: 'authoriser', type: 'address' },
      { internalType: 'address', name: 'delegate', type: 'address' },
    ],
    name: 'canBurnFor',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x7d3f0ba2',
  },
  {
    constant: true,
    inputs: [
      { internalType: 'address', name: 'authoriser', type: 'address' },
      { internalType: 'address', name: 'delegate', type: 'address' },
    ],
    name: 'canClaimFor',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x21f4ae57',
  },
  {
    constant: true,
    inputs: [
      { internalType: 'address', name: 'authoriser', type: 'address' },
      { internalType: 'address', name: 'delegate', type: 'address' },
    ],
    name: 'canExchangeFor',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xfaf431bb',
  },
  {
    constant: true,
    inputs: [
      { internalType: 'address', name: 'authoriser', type: 'address' },
      { internalType: 'address', name: 'delegate', type: 'address' },
    ],
    name: 'canIssueFor',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x04872617',
  },
  {
    constant: true,
    inputs: [],
    name: 'eternalStorage',
    outputs: [
      {
        internalType: 'contract EternalStorage',
        name: '',
        type: 'address',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x98ff9c54',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: '_owner', type: 'address' }],
    name: 'nominateNewOwner',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x1627540c',
  },
  {
    constant: true,
    inputs: [],
    name: 'nominatedOwner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x53a47bb7',
  },
  {
    constant: true,
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x8da5cb5b',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: 'delegate', type: 'address' }],
    name: 'removeAllDelegatePowers',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x6f95200b',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: 'delegate', type: 'address' }],
    name: 'removeBurnOnBehalf',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x59cec3d6',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: 'delegate', type: 'address' }],
    name: 'removeClaimOnBehalf',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x6c8bc9fe',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: 'delegate', type: 'address' }],
    name: 'removeExchangeOnBehalf',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xb9156efa',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: 'delegate', type: 'address' }],
    name: 'removeIssueOnBehalf',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x431ce540',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'contract EternalStorage',
        name: '_eternalStorage',
        type: 'address',
      },
    ],
    name: 'setEternalStorage',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xb5bb5619',
  },
];
